---
- hosts: all
  connection: ssh
  become: yes
  vars:
    abc: httpd

  tasks:
    - name: Install httpd
      yum:
        name: "{{ abc }}"
        state: present
      notify: start httpd

  handlers:
    - name: start httpd
      service:
        name: "{{ abc }}"
        state: started
