---
- hosts: all
  connection: ssh
  variables
  {
  abc=httpd
  
  }
  
  tasks:
    - name: install http
     yum: {{abc}} state=present
	 notify: start httpd
 handlers:
    - name: start htttpd
     service: name={{abc}} state=started
